
# 在config-server，可以通过访问 http://localhost:8900/config-client.yml来看配置信息
# URL与配置文件的映射关系如下：
#   /{application}/{profile}[/{label}]
#   /{application}-{profile}.yml
#   /{label}/{application}-{profile}.yml
#   /{application}-{profile}.properties
#   /{label}/{application}-{profile}.properties
#   上面的url会映射{application}-{profile}.properties对应的配置文件，{label}对应git上不同的分支，默认为master。

server:
  port: 8100
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
      #defaultZone: http://192.168.3.200:8888/eureka/
  instance:
    prefer-ip-address: true # 将自己的IP注册到Eureka Server。若不配置或设置为false，表示注册微服务所在操作系统的hostname到Eureka Server

        
management:  #actuator
  server:
    port: 8200
  endpoints:
    enabled-by-default: true  # 开启actuator
    web:
      base-path: /actuator #默认是/actuator 前缀，可以在这里修改
      exposure:
        include: "*"  #打开全部请求端点
#        include: refresh,health,info #打开部分
  security:
    enabled: false     #SpringBoot 1.5.X 以上默认开通了安全认证，如果不关闭会要求权限
